#include "i2s_audio.h"
#include "sai.h"
#include "usart.h"
#include "stm32h7xx_hal.h"

// -------------------------- Configuration ----------------------------
#define AUDIO_BUFFER_SIZE 1024   // DMA buffer size (number of 32-bit samples)
#define CIRCULAR_BUFFER_SIZE 2048 // Size of circular buffer to hold captured samples

// -------------------------- Buffers ----------------------------
// DMA double-buffered reception
static uint32_t i2s_rx_buffer[AUDIO_BUFFER_SIZE];

// Circular buffer for processed audio
static uint32_t circular_buffer[CIRCULAR_BUFFER_SIZE];
static volatile uint32_t circ_write_idx = 0;
static volatile uint32_t circ_sample_count = 0;

// -------------------------- Flags ----------------------------
volatile uint8_t new_samples_ready = 0; // signal main loop

// -------------------------- Initialization ----------------------------
void I2S_Audio_Init(void)
{
    // Initialize SAI peripheral (generated by CubeMX)
    MX_SAI1_Init();

    // Start DMA reception
    if (HAL_SAI_Receive_DMA(&hsai_BlockA1,
                            (uint8_t *)i2s_rx_buffer,
                            AUDIO_BUFFER_SIZE) != HAL_OK)
    {
        Error_Handler();
    }
}

// -------------------------- DMA Callbacks ----------------------------
void HAL_SAI_RxHalfCpltCallback(SAI_HandleTypeDef *hsai)
{
    if (hsai->Instance == SAI1_Block_A)
    {
        // Copy first half of DMA buffer to circular buffer
        for (uint32_t i = 0; i < AUDIO_BUFFER_SIZE / 2; i++)
        {
            circular_buffer[circ_write_idx] = i2s_rx_buffer[i];
            circ_write_idx = (circ_write_idx + 1) % CIRCULAR_BUFFER_SIZE;
            if (circ_sample_count < CIRCULAR_BUFFER_SIZE)
                circ_sample_count++;
        }
        new_samples_ready = 1; // signal main loop
    }
}

void HAL_SAI_RxCpltCallback(SAI_HandleTypeDef *hsai)
{
    if (hsai->Instance == SAI1_Block_A)
    {
        // Copy second half of DMA buffer to circular buffer
        for (uint32_t i = AUDIO_BUFFER_SIZE / 2; i < AUDIO_BUFFER_SIZE; i++)
        {
            circular_buffer[circ_write_idx] = i2s_rx_buffer[i];
            circ_write_idx = (circ_write_idx + 1) % CIRCULAR_BUFFER_SIZE;
            if (circ_sample_count < CIRCULAR_BUFFER_SIZE)
                circ_sample_count++;
        }
        new_samples_ready = 1; // signal main loop
    }
}

// -------------------------- Processing ----------------------------
// Weak user-implemented function (override if needed)
__weak void I2S_Audio_Process(uint32_t *samples, uint32_t num_samples)
{
    // Default: store in circular buffer (done in DMA callback)
}

// -------------------------- Main Loop Helper ----------------------------
// Call this in main() loop to safely read samples
uint32_t I2S_GetSample(void)
{
    static uint32_t read_idx = 0;
    uint32_t sample = 0;

    if (circ_sample_count > 0)
    {
        sample = circular_buffer[read_idx];
        read_idx = (read_idx + 1) % CIRCULAR_BUFFER_SIZE;
        __disable_irq();
        circ_sample_count--;
        __enable_irq();
    }
    return sample;
}
